# Generated by Django 3.2.13 on 2022-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('period', models.CharField(default='now', max_length=20)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'form',
            },
        ),
    ]
