# Generated by Django 3.2.13 on 2022-04-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formmodel',
            name='period',
            field=models.CharField(default='now', max_length=20),
        ),
    ]
