# Generated by Django 3.2.13 on 2022-04-20 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_formmodel_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formmodel',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='formmodel',
            name='url',
        ),
        migrations.AddField(
            model_name='formmodel',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
